INSERT INTO role (name, info)
VALUES
	("HELPDESK", "RESPONSIBLE FOR INCOMING REQUEST/ISSUES"),
	("CASHIER", "RESPONSIBLE CASHFLOW"),
	("HEAD CHEF", "RESPONSIBLE FOR MAIN COURSES"),
  ("SOUS CHEF", "RESPONSIBLE FOR SIDE-DISHES");
